export const AdminPaths = {
  authLogin: "/admin/auth/login",
  authBootstrap: "/admin/auth/bootstrap",
  authMe: "/admin/auth/me",
  dashboard: "/admin/dashboard",
  users: "/admin/users",
  usersOnline: "/admin/users/online",
  usersRecent: "/admin/users/recent",
  user: (id: string) => `/admin/users/${id}`,
  reports: "/admin/reports",
  report: (id: string) => `/admin/reports/${id}`,
  reportClose: (id: string) => `/admin/reports/${id}/close`,
  bugs: "/admin/bugs",
  moderationPhotos: "/admin/moderation/photos",
  moderationPhoto: (id: string) => `/admin/moderation/photos/${id}`,
  moderationMessages: "/admin/moderation/messages",
  matches: "/admin/matches",
  chatConversations: "/admin/chat/conversations",
  chatConversation: (id: string) => `/admin/chat/conversations/${id}`,
  notifications: "/admin/notifications",
  statsOverview: "/admin/stats/overview",
  statsUsers: "/admin/stats/users",
  statsActivity: "/admin/stats/activity",
  statsMatches: "/admin/stats/matches",
  statsMessages: "/admin/stats/messages",
  statsSwipes: "/admin/stats/swipes",
  statsRetention: "/admin/stats/retention",
  statsGender: "/admin/stats/gender",
  statsAgeGroups: "/admin/stats/age-groups",
  statsGeography: "/admin/stats/geography",
  statsRevenue: "/admin/stats/revenue",
  health: "/admin/health",
  auditLogs: "/admin/audit/logs",
} as const;
