export const AdminPaths = {
  authLogin: "/admin/auth/login",
  authBootstrap: "/admin/auth/bootstrap",
  authMe: "/admin/auth/me",
  users: "/admin/users",
  user: (id: string) => `/admin/users/${id}`,
  reports: "/admin/reports",
  report: (id: string) => `/admin/reports/${id}`,
  reportClose: (id: string) => `/admin/reports/${id}/close`,
  moderationPhotos: "/admin/moderation/photos",
  moderationPhoto: (id: string) => `/admin/moderation/photos/${id}`,
  moderationMessages: "/admin/moderation/messages",
  matches: "/admin/matches",
  chatConversations: "/admin/chat/conversations",
  chatConversation: (id: string) => `/admin/chat/conversations/${id}`,
  notifications: "/admin/notifications",
  statsUsers: "/admin/stats/users",
  statsGender: "/admin/stats/gender",
  statsAgeGroups: "/admin/stats/age-groups",
  statsGeography: "/admin/stats/geography",
  statsRevenue: "/admin/stats/revenue",
  health: "/admin/health",
  auditLogs: "/admin/audit/logs",
} as const;
